export const gameHeight = 1200;
export const gameWidth = 900;
export const widthHeightRatio = .75;
export const heightWidthRatio = 1.33;
export const baseGfxHeight = 207; //This is what InkScape generally drew it as
export const baseGfxWidth = 201; //This is what InkScape generally drew it as
export const activeBulletCount = 1;
export const bulletLength = 4.4767156;
export const bulletWidth = 0.78343964;
export const bulletVelocity = 2;
export const shipBarrelLength = 1.90261;
export const shipPosGunOffset = 0.70882;
export const shipWidth = 4.75;
export const shipMoveRate = 2;
export const shipPylongWiggleDist = .5;
export const shipPylongWiggleSpeed = 1;
