export const gameHeight = 1200;
export const gameWidth = 900;
export const widthHeightRatio = .75;
export const heightWidthRatio = 1.33;
export const baseGfxHeight = 207; //This is what InkScape generally drew it as
export const baseGfxWidth = 201; //This is what InkScape generally drew it as
export const shipWidth = 4.75;
export const shipMoveRate = 2;
export const shipPylongWiggleDist = .5;
export const shipPylongWiggleSpeed = 1;
export const fireVelocity = 10;